### ISSUE TITLE
Add scheduled task to generate automatically new artifacts to download

### ISSUE THREAD

**Issue by qarmin** [GodotECS/godex#273]
In my one project, this task looks in this way
```
name: 🐧 Godot 3.x Exported Debug
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  linux-exported-debug:
    runs-on: "ubuntu-20.04"
    name: Editor and project
```
This will run 1 time per day
https://crontab.guru/ should help to find the most optimal settings
